### PR TITLE
Add second-level timestamp bit

### PR DESCRIPTION
**Pull request by hafung**

### CODE REVIEW

**Comment by godruoyi** [comment]
thank your PR, but could you please update the PR description detail? I don't know what this PR does.

Also, please fix the CI error.

**Comment by godruoyi** [comment]
#34

**Comment by godruoyi** [comment]
It looks like it provides a 53bit snowflake ID implementation If I understand it right, hmm... I don't think I can accept it because it's too limiting, maybe only you need this; so do you plan to make it more flexible?

Anyway, thanks for your PR, and if you just want to implement a 53bit snowflake ID, I suggest you go ahead and do it directly in your owner project. thanks.

**Comment by hafung** [comment]
> It looks like it provides a 53bit snowflake ID implementation If I understand it right, hmm (嗯) ... I don't think I can accept it because it's too limiting, maybe only you need this; so do you plan to make it more flexible?
> 
> Anyway, thanks for your PR, and if you just want to implement a 53bit snowflake ID, I suggest you go ahead and do it directly in your owner project. thanks.

okay... make sense indeed... i thought i just  add a stand-alone option, it would do no harm. anyway, that's fine

**Pull request closed without merging**
